### ISSUE TITLE
Classic Theme

### ISSUE THREAD

**Issue by wachilt** [wachilt/kirby-themes#132]
**Details** https://gumroad.com/l/oKVnu
**Live demo** http://kc.konstantin.fr/classic-theme

> **Classic is a clean theme for the cms Kirby. Use it as a personnal or a professional website to show your projects, informations, collaborators etc. Classic has all you need to start your web showcase with a modern and light design.**

![le_classic_-_2017-05-08_22 10 03](https://cloud.githubusercontent.com/assets/2782385/25825582/5e719646-343b-11e7-8f1f-42e52a30a7b6.png)

**Comment by demlak** [comment]
demo server down
purchaselink 404
