### ISSUE TITLE
Ma petite Entreprise (MPE)

### ISSUE THREAD

**Issue by wachilt** [wachilt/kirby-themes#135]
**Details** https://gumroad.com/l/jFKcS
**Live demo** https://www.cj-lab.fr/themes/mpe

> **Ma Petite Entreprise (MPE) is a theme for the CMS Kirby build to show your local business on the Web. It can be easily adapted to any kind of activity. Theme is not built to sell products online, it is a Showcase/Vitrine website.**

![ma_petite_entreprise_home_-_2017-05-31_14 09 04](https://cloud.githubusercontent.com/assets/2782385/26633389/23ee0874-460b-11e7-88e0-207cd9e9c024.png)

**Comment by demlak** [comment]
demo server down
purchase link 404
