### ISSUE TITLE
Streamline

### ISSUE THREAD

**Issue by wachilt** [wachilt/kirby-themes#136]
**Details** https://creativemarket.com/11bits/1566928-Streamline-Kirby-Theme
**Live demo** http://demo.11bits.es/streamline-for-kirby

> **Streamline is a minimalist blog theme for Kirby CMS.**

![streamline_blog_-_2017-06-02_11 01 57](https://cloud.githubusercontent.com/assets/2782385/26721856/74d4db34-4785-11e7-90ea-3e7dfa0a172f.png)

**Comment by demlak** [comment]
demo server 404
purchaselink redirects to main page
