### ISSUE TITLE
HROM

### ISSUE THREAD

**Issue by wachilt** [wachilt/kirby-themes#137]
**Details** https://gumroad.com/l/hrom
**Live demo** http://hdodov.net/themes/hrom

> **HROM is a responsive Kirby CMS theme with emphasis on color and photos, designed to show your stuff in all its beauty.**
> 
> **Although simple, it's also quite configurable as well. You have control over any color or image on the site. It also utilizes SCSS, allowing you to change fonts and whitespace in a jiffy.**

![hrom_ _home_-_2017-06-12_23 10 02](https://user-images.githubusercontent.com/2782385/27057689-18f73a76-4fc5-11e7-9a6d-baa37f477b96.png)

**Comment by demlak** [comment]
demo server down
