### ISSUE TITLE
Symmetric

### ISSUE THREAD

**Issue by wachilt** [wachilt/kirby-themes#153]
**Details** https://gumroad.com/l/yObtl
**Live demo** https://www.cj-lab.fr/themes/symmetric

> **Symmetric is a full portfolio and blog theme made with and for the CMS Kirby.**

![screen shot 2017-09-30 at 12 07 58-fullpage](https://user-images.githubusercontent.com/2782385/31045290-1c4ad5f2-a5d8-11e7-9645-36ffd9678d95.png)

**Comment by demlak** [comment]
Server down, Gumroadlink down
