### ISSUE TITLE
@512-1 (One page version of @512 theme)

### ISSUE THREAD

**Issue by wachilt** [wachilt/kirby-themes#213]
**Details** https://github.com/constantinjoly/512-1
**Live demo** https://www.themes.constantinweb.com/512-1

> **The theme is light, responsive, fast and easy to use, with an administration interface that will allow you to manage the content of your site with ease.**

![Screen Shot 2020-05-16 at 19 33 30-fullpage](https://user-images.githubusercontent.com/2782385/82127561-71584200-97ac-11ea-84f9-5a8d3f6d843c.png)

**Comment by constantinjoly** [comment]
Hi John, thank you for having added theme in the list. Theme is now on [github](https://github.com/constantinjoly/512-1) and Gumroad link will not work anymore soon.

**Comment by wachilt** [comment]
Hi @constantinjoly

You're welcome, and I have now updated links. :)

**Comment by constantinjoly** [comment]
Thank you

**Comment by demlak** [comment]
Theme/Repo is dead since more than two years

**Comment by wachilt** [comment]
👍

**Comment by iolla-net** [comment]
unreachable
