### ISSUE TITLE
Adana

### ISSUE THREAD

**Issue by wachilt** [wachilt/kirby-themes#214]
**Details** http://aristotheme.com/freemiums
**Live demo** http://aristotheme.com/adana

> **Clean, beautiful and minimal blog theme, made with Shuffle Pro.**

![Screen Shot 2020-08-25 at 14 04 51-fullpage](https://user-images.githubusercontent.com/2782385/91178454-0d171980-e6dd-11ea-9bce-d743b23e469b.png)

**Comment by b0rt** [comment]
Hi there,

the links are gone

**Comment by wachilt** [comment]
Hi @b0rt

Thanks once again for the heads-up.
No longer available - issue now closed.
