### ISSUE TITLE
Grafiker

### ISSUE THREAD

**Issue by wachilt** [wachilt/kirby-themes#218]
**Details** https://clicktonext.com/themes/grafiker
**Live demo** https://demo.clicktonext.com/grafiker

> **Grafiker is a minimal portfolio template built for Kirby CMS.**

![grafiker](https://user-images.githubusercontent.com/2782385/165096011-d1032adc-3cc2-4354-a89d-edf3ed2fc081.jpg)

**Comment by demlak** [comment]
links are dead

**Comment by wachilt** [comment]
👍

**Comment by iolla-net** [comment]
unreachable
