### ISSUE TITLE
Mamalika

### ISSUE THREAD

**Issue by wachilt** [wachilt/kirby-themes#219]
**Details** https://clicktonext.com/themes/mamalika
**Live demo** https://demo.clicktonext.com/mamalika

> **Mamalika is a theme for restaurants and cafes built for Kirby CMS.**

![mamalika](https://user-images.githubusercontent.com/2782385/165096133-f57e1919-af95-4b7b-9b3b-c024490c1940.jpg)

**Comment by demlak** [comment]
link dead.. like all "clicktonext" based themes..

**Comment by wachilt** [comment]
👍

**Comment by iolla-net** [comment]
unreachable
