### ISSUE TITLE
Notlar

### ISSUE THREAD

**Issue by wachilt** [wachilt/kirby-themes#220]
**Details** https://clicktonext.com/themes/notlar
**Live demo** https://demo.clicktonext.com/notlar

> **Notlar is minimal style blog/magazine theme built for Kirby CMS.**

![notlar](https://user-images.githubusercontent.com/2782385/165096230-cd43ba6b-4bfd-4cef-ad7c-968e6044f8e4.jpg)

**Comment by iolla-net** [comment]
unreachable
