### ISSUE TITLE
Firma

### ISSUE THREAD

**Issue by wachilt** [wachilt/kirby-themes#221]
**Details** https://clicktonext.com/themes/firma
**Live demo** https://demo.clicktonext.com/firma

>**Firma is a theme for business.**

![firma](https://user-images.githubusercontent.com/2782385/165096318-39eac8eb-d276-44e1-8c88-b67f5557b640.jpg)

**Comment by wachilt** [comment]
URLs are 404

**Comment by iolla-net** [comment]
unreachable
