### ISSUE TITLE
Mimar

### ISSUE THREAD

**Issue by wachilt** [wachilt/kirby-themes#222]
**Details** https://clicktonext.com/themes/mimar
**Live demo** https://demo.clicktonext.com/mimar

> **Mimar is a theme for architect.**

![Screen Shot 2022-06-11 at 09 03 42-fullpage](https://user-images.githubusercontent.com/2782385/173179370-cf2989d0-f298-4e94-a896-0a162d37e0cb.png)

**Comment by wachilt** [comment]
URLs are 404

**Comment by iolla-net** [comment]
unreachable
